export const resumeData = [
  {
    title: "Software Engineer",
    company: "Lorem Ipsum Inc.",
    location: "New York, NY",
    type: "Full-time",
    startDate: "January 2020",
    endDate: "Present",
    responsibilities: [
      "Developed and maintained web applications using React and Node.js.",
      "Collaborated with cross-functional teams to define, design, and ship new features.",
      "Wrote unit and integration tests to ensure high code quality.",
      "Participated in code reviews and provided constructive feedback.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Dolor Sit Amet LLC",
    location: "San Francisco, CA",
    type: "Contract",
    startDate: "June 2018",
    endDate: "December 2019",
    responsibilities: [
      "Built responsive and interactive user interfaces using HTML, CSS, and JavaScript.",
      "Worked closely with designers to implement pixel-perfect designs.",
      "Optimized web applications for maximum speed and scalability.",
      "Conducted user testing and gathered feedback to improve usability.",
    ],
  },
  {
    title: "Backend Developer",
    company: "Consectetur Adipiscing Corp.",
    location: "Austin, TX",
    type: "Part-time",
    startDate: "March 2017",
    endDate: "May 2018",
    responsibilities: [
      "Designed and implemented RESTful APIs using Express.js.",
      "Integrated third-party services and APIs.",
      "Managed and maintained databases using MongoDB and PostgreSQL.",
      "Troubleshooted and resolved production issues.",
    ],
  },
  {
    title: "Full Stack Developer",
    company: "Elit Industries",
    location: "Seattle, WA",
    type: "Full-time",
    startDate: "July 2015",
    endDate: "February 2017",
    responsibilities: [
      "Developed end-to-end web applications using MERN stack.",
      "Implemented authentication and authorization mechanisms.",
      "Collaborated with product managers to define technical requirements.",
      "Conducted performance tuning and optimization.",
    ],
  },
  {
    title: "Mobile App Developer",
    company: "Sed Do Eiusmod Inc.",
    location: "Los Angeles, CA",
    type: "Internship",
    startDate: "May 2014",
    endDate: "August 2015",
    responsibilities: [
      "Developed and maintained mobile applications for iOS and Android.",
      "Worked with designers to create intuitive and user-friendly interfaces.",
      "Implemented push notifications and real-time data updates.",
      "Conducted code reviews and ensured adherence to best practices.",
    ],
  },
];
